class AddLessonsViewModel {
  List<String> fizikKonuBasliklari = [
    "Fizik Bilimine Giriş",
    "Madde ve Özellikleri",
    "Hareket ve Kuvvet",
    "Enerji",
    "Isı ve Sıcaklık",
    "Elektrostatik",
    "Elektrik Akımı ve Devreleri",
    "Mıknatıslar ve Manyetizma",
    "Basınç",
    "Kaldırma Kuvveti",
    "Dalgalara Giriş ve Yay Dalgaları",
    "Su, Ses ve Deprem Dalgaları",
    "Aydınlanma, Gölge ve Düzlem Aynalar",
    "Küresel Aynalar",
    "Vektörler",
    "Bağıl Hareket",
    "Newton'un Hareket Yasaları",
    "Bir Boyutta Sabit İvmeli Hareket",
    "Atışlar",
    "İş, Güç ve Enerji II",
    "İtme ve Momentum",
    "Kuvvet, Tork ve Denge",
    "İş, Güç ve Enerji III",
    "Hareket ve Enerji",
    "Dairesel Hareket",
    "Mekanik Dalgalar",
    "Optik",
    "Isı ve Termodinamik",
    "Elektrik ve Manyetizma",
    "Modern Fizik",
  ];

  List<String> matematikKonuBasliklari = [
    "Kesirler",
    "Eşitlikler ve Eşitsizlik Denklemleri",
    "Fonksiyonlar ve Grafikler",
    "Sayılar Teorisi",
    "Denklemler ve Eşitsizlikler",
    "Geometri",
    "İstatistik ve Olasılık",
    "Limitler ve Türevler",
    "İntegraller",
    "Türevler ve Uygulamaları",
    "İntegraller ve Uygulamaları",
    "Diferansiyel Denklemler",
    "Kombinatorik ve Olasılık",
    "Analitik Geometri",
    "Lineer Cebir",
  ];
}
