// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQEydJDrP-OfzarVcTR0t5rH33RiLYuYQ',
    appId: '1:423690618353:web:a7727adbc9825a70f37050',
    messagingSenderId: '423690618353',
    projectId: 'quiz-app-aff44',
    authDomain: 'quiz-app-aff44.firebaseapp.com',
    storageBucket: 'quiz-app-aff44.appspot.com',
    measurementId: 'G-HZCBY2YEYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOwAgy9ts7aXq5cb7EGeuaktT0gACXSM',
    appId: '1:423690618353:android:00907c09ca70e38ef37050',
    messagingSenderId: '423690618353',
    projectId: 'quiz-app-aff44',
    storageBucket: 'quiz-app-aff44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxsC_UVOhzJXXYMdNcmUFXpL9RLSdoIw',
    appId: '1:423690618353:ios:912b93051b1a9622f37050',
    messagingSenderId: '423690618353',
    projectId: 'quiz-app-aff44',
    storageBucket: 'quiz-app-aff44.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxsC_UVOhzJXXYMdNcmUFXpL9RLSdoIw',
    appId: '1:423690618353:ios:d2b3c7cfd7f9bcc9f37050',
    messagingSenderId: '423690618353',
    projectId: 'quiz-app-aff44',
    storageBucket: 'quiz-app-aff44.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
